version: '3.3'

services:
   sqlserver:
     image: sierracsd/mocksifdb:1.0
     container_name: "sqlserver"
     ports:
      - "1433:1433"
     environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "Qwerty2020"

   sif:
     depends_on:
       - sqlserver
     image: sierracsd/mocksif:1.0
     container_name: "sif"
     ports:
       - "80:80"
       - "443:443"
