version: '3.3'

services:
   sqlserver:
     image: sierracsd/mocksifdb:1.2
     container_name: "sqlserver"
     networks:
      - mocksif
     ports:
      - "1433:1433"
     environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "Qwerty2020"

   sif:
     depends_on:
       - sqlserver
     image: sierracsd/sifapisandbox:latest
     container_name: "sif"
     networks:
      - mocksif
     ports:
       - "80:80"
       - "443:443"
networks: 
  mocksif: